import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { Button } from '@/components/ui/button'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Pypestore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} font-sans text-ground`}>
        <main className="bg-[url('assets/home.png')] bg-cover bg-fixed bg-center min-h-screen">
          <header className='flex items-center justify-between py-2 px-4 shadow-xl bg-slate-200'>
            <Button variant='outline' className='font-bold border-ground border-2 rounded-sm'>
              Pypestore
            </Button>

            <ul className='flex items-center gap-8 text-xs font-medium'>
              <li>Home</li>
              <li>Products</li>
              <li>Contact Us</li>
            </ul>
          </header>

          {children}
        </main>
      </body>
    </html>
  )
}
