import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { ShoppingBag } from "lucide-react";
import MenuList from "@/components/menu-list";
import { Filter } from "@/providers/filter";
import { Query } from "@/providers/query";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Pypestore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} font-sans text-ground`}>
        {/* query client provider */}
        <Query>
          {/* filter context provider */}
          <Filter>
            <main className="bg-[url('../assets/home.png')] bg-cover bg-fixed bg-center min-h-screen">
              <header className="flex items-center justify-between py-2 px-32 shadow-xl bg-zinc-100">
                <Button
                  variant="outline"
                  className="font-bold border-ground border-2 rounded-sm"
                >
                  Pypestore
                </Button>

                <MenuList />

                <ShoppingBag className="w-5 h-5" />
              </header>

              {children}
            </main>
          </Filter>
        </Query>
      </body>
    </html>
  );
}
